<?php 

# Require the AWS SDK for DynamoDB interaction, these files are generated by "composer".
require 'vendor/autoload.php';

# Include the config file
include 'config.php';

# Set errors on (/var/log/apache2/error.log)
ini_set("display_errors", "On");

#######################
## Declare functions ##
#######################

// Connect to the database, either mongodb or dynamodb
function ConnectDB($remoteData){
    global $m;
    global $awsRegion;
    global $remoteData;
    
    if($remoteData){
        // DynamoDB
        $m = Aws\DynamoDb\DynamoDbClient::factory(array(
            'region'  => (string)$awsRegion,
            'version' => "latest"
        ));
    } else {
        // MongoDB
        $username="student";
        $password="Cloud247";
        $servername="localhost";
        
        $m = new \MongoDB\Driver\Manager("mongodb://${username}:${password}@${servername}/memegen");
    }
}

// Inserts a meme name and current date into the database, either mongodb or dynamodb
function InsertMemes($remoteData, $imageName){
    global $m;
    global $yourId;
    global $remoteData;
    
    $rand = rand(1,99999999);
    $time = time();
      
    if($remoteData){
        // DynamoDB
            $yourTable = "images-" . $yourId;
            
            // Insert data in the images table
            $insertResult = $m->putItem(array(
                'TableName' => "$yourTable",
                'Item' => array(
                    'id'      => array('N' => (string)$rand),
                    'name'    => array('S' => $imageName),
                    'date'    => array('S' => (string)$time)
                )
            ));
    } else {
        // MongoDB
            // Insert into memegen db and images collection
            $bulk = new MongoDB\Driver\BulkWrite;
            $bulk->insert([ 
                            'id'    => array('N' => $rand), # This cannot be a string
                            'name'  => array('S' => $imageName), 
                            'date'  => array('S' => (string)$time)
                          ]);
            $m->executeBulkWrite('memegen.images', $bulk);
    }
}

// Gets all memes and encodes and echo's it so ajax can catch it.
function GetMemes($remoteData){
    global $m;
    global $yourId;
    global $s3Bucket;
    global $remoteFiles;
    global $remoteData;
  
    // If files are stored remotely (s3), sync them first to local dir
    if($remoteFiles){
        // sync from s3
        $command = "aws s3 sync s3://$s3Bucket meme-generator-python/memes/ 2>&1";
        $commandoutput = exec($command, $out, $status);
    }
  
    // If data is stored remotely, use dynamodb, else mongodb
    if($remoteData){
        // DynamoDB
        $yourTable = "images-" . $yourId;
        
        $iterator = $m->getIterator('Scan', array(
          'TableName' => "$yourTable"
        ));
        
        echo json_encode(iterator_to_array($iterator));
    } else {
        // MongoDB
        $filter = ['id.N' => ['$gt' => 0]];
        $options = [];
        $query = new MongoDB\Driver\Query($filter, $options);
        $iterator = $m->executeQuery('memegen.images', $query); 

        echo json_encode(iterator_to_array($iterator));
    }
}

// Generates a meme with the python script and either puts it locally or in an S3 bucket
function generateMeme($remote, $top, $bot, $imgname){
    global $m;
    global $s3Bucket;
    global $remoteFiles;
  
    # Save current dir and go into python dir
    $olddir = getcwd();
    chdir("meme-generator-python");
    
    # Create full imagenames
    $rand = rand(1,999);
    $imgnameorig = $imgname . ".jpg";
    # No extension variable image name
    $imgnametargetnoext = $imgname . "-" . $top . "-" . $bot . "-" . $rand;
    # Replace nasty characters
    $imgnametargetnoext = preg_replace('/[^-.0-9\w]+/', '', $imgnametargetnoext);
    # With extension variable image name
    $imgnametargetwithext = $imgnametargetnoext . ".jpg";
    
    # Execute meme generator python command
    $command = "python memegen.py '$top' '$bot' '$imgnameorig' '$imgnametargetwithext' 2>&1";
    $commandoutput = exec($command, $out, $status);
    
    # Go back to original dir
    chdir($olddir);
    
    # Sync images remotely (s3)
    if($remoteFiles){
        // sync to s3
        $command = "aws s3 sync meme-generator-python/memes/ s3://$s3Bucket 2>&1";
        $commandoutput = exec($command, $out, $status);
    }

    return $imgnametargetnoext;
}

?>